### ISSUE TITLE
Unregistered User can access directory of all users

### ISSUE THREAD

**Issue by boveus** [gsu-library/sirenia#52]
@here I've just become aware that Hyrax has a public `users` index that lists all registered users https://nurax.curationexperts.com/users

It looks like the /users path lists all user accounts.  I think this would be a simple fix of adding "cannot view Users" or something to our Ability.rb file to prevent unregistered users from accessing this page.  That is if we consider this a security issue.

**Comment by ewilloughby** [comment]
I vote for requiring someone at a minimum to be logged in with a role of Uploader/Administrator in order to access this page.  I don't think anyone would assume that because they are a member of the system, their email address is publicly available. I don't forsee any need to for this list to be public.

**Comment by boveus** [comment]
This would require modifying (overriding) the Hyrax::UserController.  I think it would be useful to disable this feature, but it sounds like it is being worked on for core Hyrax.  When we get to production I think it would be a good issue to address, but for now it would introduce too much maintenance if we try to override that controller.

**Comment by boveus** [comment]
This has been fixed in the version of Hyrax we are using.
